theme: jekyll-theme-midnight
title: "Vacation to Cancun"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "March 1 to March 8 2023"
google_analytics:
